//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle.Allocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vaAccount()
        {
            this.vaOffers = new HashSet<vaOffer>();
            this.vaRequests = new HashSet<vaRequest>();
        }
    
        public int PK { get; set; }
        public Nullable<int> TypeFK { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Field { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    
        public virtual vaAccountType vaAccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vaOffer> vaOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vaRequest> vaRequests { get; set; }
    }
}
