//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle.Allocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaOffer
    {
        public int PK { get; set; }
        public Nullable<int> RequestFK { get; set; }
        public Nullable<int> AccountFK { get; set; }
        public decimal Fee { get; set; }
        public bool Confirmed { get; set; }
    
        public virtual vaAccount vaAccount { get; set; }
        public virtual vaRequest vaRequest { get; set; }
    }
}
