//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle.Allocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vaRequest()
        {
            this.vaOffers = new HashSet<vaOffer>();
        }
    
        public int PK { get; set; }
        public Nullable<int> AccountFK { get; set; }
        public string Type { get; set; }
        public int Population { get; set; }
        public string Date { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public bool Confirmed { get; set; }
    
        public virtual vaAccount vaAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vaOffer> vaOffers { get; set; }
    }
}
